export const brandModels = {
  Acura: [
    "CL",
    "CSX",
    "EL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX",
  ],
  Alfa: [
    "147",
    "164 Sedan",
    "1750",
    "4C",
    "Alfetta",
    "Giulia",
    "Giulia 1600",
    "Giulietta",
    "GTV6",
    "Milano",
    "Mito",
    "Spider-1600",
    "Spider-1600 Duetto",
    "Spider-2000",
    "Stelvio",
  ],
  AMC: [
    "Ambassador",
    "American",
    "AMX",
    "Classic",
    "Concord",
    "Eagle",
    "Gremlin",
    "Hornet",
    "Javelin",
    "Marlin",
    "Matador",
    "Other",
    "Pacer",
    "Rambler",
    "Rebel",
    "Spirit",
  ],
  Aston: ["Martin"],
  Asuna: ["Asuna"],
  Audi: [
    "100",
    "200",
    "4000 2 & 4 Door Sedan",
    "4000 Quattro",
    "5000 & 5000 Quattro",
    "80 Series",
    "90 Series",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "AllRoad",
    "AllRoad A4",
    "AllRoad A6",
    "Cabriolet",
    "Coupe GT",
    "Coupe Quattro",
    "e tron",
    "Fox",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "R8",
    "RS Q8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "Sport Coupe",
    "SQ5",
    "SQ7",
    "SQ8",
    "Super 90",
    "TT",
    "V8 Quattro",
  ],
  Austin: ["Austin", "Mini"],
  Autocar: ["Autocar"],
  Avanti: ["Avanti"],
  Bentley: ["Bentley"],
  BMW: [
    "128i",
    "135i",
    "1602",
    "1800",
    "1M",
    "2002",
    "228i",
    "230i",
    "2500",
    "2800",
    "3.0",
    "318i",
    "320i",
    "323i",
    "325e",
    "325i",
    "328i",
    "328i GT",
    "330e",
    "330i",
    "330i GT",
    "335i",
    "335i GT",
    "340i",
    "340i GT",
    "428i",
    "430i",
    "435i",
    "440i",
    "524TD",
    "525i",
    "528e",
    "528i",
    "530e",
    "530i",
    "533i",
    "535i",
    "535i GT",
    "540i",
    "545i",
    "550i",
    "550i GT",
    "630CSi",
    "633CSi",
    "635CSi",
    "640i",
    "640i GT",
    "645Ci",
    "650i",
    "728",
    "732",
    "733i",
    "735i",
    "740e",
    "740i",
    "745e",
    "745i",
    "750i",
    "760i",
    "840ci",
    "840i",
    "850i",
    "ActiveE",
    "ActiveHybrid 3",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "Alpina B6",
    "Alpina B7",
    "Alpina B8",
    "Alpina XB7",
    "I3",
    "I4",
    "I8",
    "IX",
    "L6",
    "M1",
    "M2",
    "M235i",
    "M240i",
    "M3",
    "M340i",
    "M4",
    "M440i",
    "M5",
    "M550i",
    "M6",
    "M760i",
    "M8",
    "M850i",
    "Mini Cooper",
    "Mini Cooper Clubman",
    "Mini Cooper Countryman",
    "Mini Cooper Paceman",
    "Other",
    "X1",
    "X2",
    "X3",
    "X3M",
    "X4",
    "X4M",
    "X5",
    "X5M",
    "X6",
    "X6M",
    "X7",
    "Z3",
    "Z4",
    "Z8",
  ],
  Bricklin: ["Bricklin"],
  Brockway: ["Brockway"],
  Buick: [
    "Allure",
    "Apollo",
    "Cascada",
    "Century",
    "Electra (1979 Down)",
    "Electra (1980 Up)",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Lacrosse",
    "LeSabre (1979 Down)",
    "LeSabre (1980 Up)",
    "Limited",
    "Lucerne",
    "Other",
    "Park Ave (1979 Down)",
    "Park Ave (1980 Up)",
    "Rainier",
    "Reatta",
    "Regal",
    "Regal Somerset (1984 Down)",
    "Rendezvous",
    "Riviera",
    "Roadmaster (1979 Down)",
    "Roadmaster (1980 Up)",
    "Skyhawk",
    "Skylark",
    "Somerset (1985 Up)",
    "Special",
    "Terraza",
    "Verano",
  ],
  Cadillac: [
    "Allante",
    "ATS",
    "Brougham",
    "Catera",
    "Cimarron",
    "Concours",
    "CT4",
    "CT5",
    "CT6",
    "CTS",
    "DeVille (1979 Down)",
    "DeVille (1980 Up)",
    "DHS",
    "DTS (2005 Down)",
    "DTS (2006 Up)",
    "Eldorado (1966 Down)",
    "Eldorado (1967 Up)",
    "ELR",
    "Escalade",
    "Escalade-ESV",
    "Escalade-EXT",
    "Fleetwood (1979 Down)",
    "Fleetwood (1980 Up)",
    "Other",
    "Seville (incl STS)",
    "SRX",
    "STS",
    "XLR",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
  ],
  Checker: ["Cab", "Checker"],
  Chevy: [
    "Astra",
    "Astro",
    "Aveo",
    "Beretta",
    "Blazer (2019 Up)",
    "Blazer, Full Size (1994 Down)",
    "Blazer, S10/S15",
    "Bolt",
    "Bolt EUV",
    "C2",
    "Camaro",
    "Caprice (1979 Down)",
    "Caprice (1980 Up)",
    "Captiva Sport",
    "Cavalier",
    "Celebrity",
    "Chevelle",
    "Chevette",
    "Chevy Pickup FWD (Non US Mkt)",
    "Chevy Small Car (Non US Mkt)",
    "Citation",
    "City Express",
    "Cobalt",
    "Corsa",
    "Corsica",
    "Corvair",
    "Corvette",
    "Cruze",
    "El Camino (1963 Down)",
    "El Camino (1964-1977)",
    "El Camino (1978 Up)",
    "Epica",
    "Equinox",
    "HHR",
    "Impala (1979 Down)",
    "Impala (1980 Up)",
    "Lumina Car",
    "Lumina Van",
    "Luv (See Also Isuzu Mini P-Up)",
    "Malibu",
    "Meriva",
    "Metro",
    "Monte Carlo",
    "Monza",
    "Nova & Chevy II (1967 Down)",
    "Nova (1968 Up)",
    "Optra",
    "Orlando",
    "Other",
    "Prizm",
    "S10/S15/Sonoma",
    "Sonic",
    "Spark",
    "Spectrum",
    "Sprint",
    "SS",
    "SSR",
    "Suburban-10 (1988 Down)",
    "Suburban-1000 (1963-1966)",
    "Suburban-1500",
    "Suburban-20 (1988 Down)",
    "Suburban-2500 (1967 Up)",
    "Suburban-30 (1966 Down)",
    "Suburban-3500",
    "Tahoe",
    "Tigra",
    "Tornado",
    "Tracker",
    "TrailBlazer",
    "TrailBlazer-EXT",
    "Traverse",
    "Trax",
    "Truck-10 Series (1987 Down)",
    "Truck-1500 Series (1988-1999)",
    "Truck-20 Series (1988 Down)",
    "Truck-2500 Series (1988-2000)",
    "Truck-30 Series (1988 Down)",
    "Truck-3500 Series (1988-2001)",
    "Truck-Avalanche 1500",
    "Truck-Avalanche 2500",
    "Truck-C3100",
    "Truck-C3600",
    "Truck-C3800",
    "Truck-Colorado",
    "Truck-Forward Control",
    "Truck-Kodiak",
    "Truck-Luv Mini Pup",
    "Truck-S10/S15/Sonoma",
    "Truck-Silverado 1500 (1999 Up)",
    "Truck-Silverado 2500 (1999 Up)",
    "Truck-Silverado 3500 (2001 Up)",
    "Truck-Tilt Cab",
    "Uplander",
    "Van 10",
    "Van 20",
    "Van 30",
    "Van Express 1500",
    "Van Express 2500",
    "Van Express 3500",
    "Vectra",
    "Vega",
    "Venture",
    "Volt",
    "Zafira",
  ],
  Chrysler: [
    "200",
    "300",
    "300M",
    "Aspen",
    "Atos",
    "Attitude",
    "Cirrus",
    "Concorde",
    "Conquest",
    "Cordoba",
    "Crossfire",
    "E Class",
    "Fifth Avenue - FWD",
    "Fifth Avenue - RWD (1979 Up)",
    "Imperial",
    "Laser",
    "Lebaron",
    "LHS",
    "New Yorker - FWD",
    "New Yorker - RWD",
    "Newport",
    "Other",
    "Pacifica",
    "Prowler",
    "PT Cruiser",
    "Sebring",
    "TC",
    "Town and Country",
    "Voyager",
  ],
  Citroen: ["Citroen"],
  Daewoo: ["Lanos", "Leganza", "Nubira"],
  Daihatsu: ["Charade", "Hijet", "Rocky"],
  Delorean: ["Delorean"],
  Desoto: ["Desoto"],
  Diamond: ["Reo"],
  Dodge: [
    "400",
    "600",
    "Aries",
    "Aspen",
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger (Chrysler)",
    "Challenger (Mitsubishi)",
    "Charger",
    "Colt Vista",
    "Colt-not Vista",
    "Cricket",
    "D50/Ram 50 (See also Plymouth Arrow Truck)",
    "Dakota",
    "Dart",
    "Daytona",
    "Diplomat",
    "Durango",
    "Dynasty",
    "Intrepid",
    "Journey",
    "Lancer",
    "Magnum",
    "Mirada",
    "Monaco (1978 Down)",
    "Monaco (1990 Up)",
    "Neon",
    "Nitro",
    "Omni",
    "Other",
    "Raider",
    "Ramcharger",
    "Rampage",
    "Shadow",
    "Spirit",
    "St Regis",
    "Stealth",
    "Stratus",
    "Truck-100 Series (1989 Down)",
    "Truck-150 (1978-1993)",
    "Truck-1500 (1994 Up)",
    "Truck-200 Series (1980 Down)",
    "Truck-250 Series (1981-1993)",
    "Truck-2500 Series (1994 Up)",
    "Truck-300 Series (1980 Down)",
    "Truck-350 Series (1981-1993)",
    "Truck-3500 (1994 Up)",
    "Truck-400 Series",
    "Truck-450 Series",
    "Truck-4500 Series",
    "Truck-5500 Series",
    "Truck-D50/Ram 50",
    "Truck-Dakota",
    "Truck-Forward Control",
    "Truck-Rampage",
    "Van (Sprinter 2500)",
    "Van (Sprinter 3500)",
    "Van 100",
    "Van 150",
    "Van 1500",
    "Van 200",
    "Van 250",
    "Van 2500",
    "Van 300",
    "Van 350",
    "Van 3500",
    "Verna",
    "Viper",
  ],
  Eagle: ["2000 GTX", "Premier", "Summit", "Talon", "Vision"],
  Edsel: ["Edsel"],
  Ferrari: ["Ferrari"],
  Fiat: [
    "1100R",
    "124 (1983 Down, includes Spider)",
    "124 Spider (2016 Up)",
    "128",
    "131/Brava",
    "500",
    "600",
    "850",
    "Other",
    "Spider (includes 2000)",
    "Strada",
    "X 1/9",
  ],
  Fisker: ["Karma"],
  Ford: [
    "500",
    "Aerostar",
    "Aspire",
    "Bronco (Full Size)",
    "Bronco II",
    "Bronco Sport",
    "C-Max",
    "Contour",
    "Cortina",
    "Courier",
    "Crown Vic (1982 Down)",
    "Crown Vic (1983 Up)",
    "Ecosport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "EXP",
    "Expedition",
    "Explorer",
    "Fairlane",
    "Fairmont",
    "Falcon",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Focus RS",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Galaxie",
    "Granada",
    "GT",
    "Ikon",
    "KA",
    "LTD (1978 Down)",
    "LTD (1979 Up)",
    "LTD II",
    "Maverick",
    "Maverick Pickup",
    "Mondeo",
    "Mustang",
    "Mustang Mach E",
    "Other",
    "Pinto",
    "Probe",
    "Ranchero (1957-1959)",
    "Ranchero (1960-1966)",
    "Ranchero (1967-1970)",
    "Ranchero (1971-1976)",
    "Ranchero (1977 up)",
    "Ranger",
    "Taurus",
    "Taurus X",
    "Tempo",
    "ThinkCity-Electric",
    "Thunderbird",
    "Torino",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit Connect",
    "Truck-Courier",
    "Truck-F100",
    "Truck-F150",
    "Truck-F150 Raptor",
    "Truck-F250 not Super Duty (1999 Down)",
    "Truck-F250 Super Duty (1999 Up)",
    "Truck-F350 not Super Duty (1997 Down)",
    "Truck-F350 Super Duty (1999 Up)",
    "Truck-F450 not Super Duty (1997 Down)",
    "Truck-F450 Super Duty (1999 Up)",
    "Truck-F550 Super Duty (1999 Up)",
    "Truck-Forward Control",
    "Truck-Ranger",
    "Van E100",
    "Van E150",
    "Van E200",
    "Van E250",
    "Van E300",
    "Van E350",
    "Van E450 Super Duty",
    "Van E550 Super Duty",
    "Windstar",
  ],
  Freightliner: ["Freightliner"],
  Freuhauf: ["Freuhauf"],
  FWD: ["Trucks"],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  Geo: ["Metro", "Prizm", "Spectrum", "Storm", "Tracker"],
  GMC: [
    "Acadia",
    "Hummer EV",
    "Jimmy, Full Size",
    "Jimmy, S10/S15",
    "Safari Van",
    "Sprint",
    "Suburban-10 (1988 Down)",
    "Suburban-1000 (1965-1966)",
    "Suburban-1500 (2001 Down)",
    "Suburban-20 (1988 Down)",
    "Suburban-2500 (1967 Up)",
    "Suburban-30 (1965-1966)",
    "Syclone",
    "Terrain",
    "Truck-1000 Series (1966 Down)",
    "Truck-1500 Series (1999 Down)",
    "Truck-2500 Series (2000 Down)",
    "Truck-3500 Series (2001 Down)",
    "Truck-Canyon",
    "Truck-Envoy",
    "Truck-Envoy XL",
    "Truck-Envoy XUV",
    "Truck-Forward Control",
    "Truck-S10/S15/Sonoma",
    "Truck-Sierra 1500 (1999 Up)",
    "Truck-Sierra 2500 (1999 Up)",
    "Truck-Sierra 3500 (2001 Up)",
    "Truck-Sierra Denali",
    "Truck-Sierra Denali 1500 (2011 Up)",
    "Truck-Sierra Denali 2500 (2011 Up)",
    "Truck-Sierra Denali 3500 (2011 Up)",
    "Truck-Topkick",
    "Truck-Yukon (except XL)",
    "Truck-Yukon XL1500",
    "Truck-Yukon XL2500",
    "Typhoon",
    "Van 1000",
    "Van 1500",
    "Van 2500",
    "Van 3500",
    "Van Savana 1500",
    "Van Savana 2500",
    "Van Savana 3500",
  ],
  Hino: ["Truck"],
  Honda: [
    "600",
    "Accord",
    "Acty",
    "Civic",
    "Clarity",
    "Clarity Electric",
    "Clarity Fuel Cell",
    "Crosstour",
    "CRV",
    "CRX",
    "CRZ",
    "DelSol",
    "Element",
    "FCX",
    "Fit",
    "HRV",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Ridgeline",
    "S2000",
  ],
  Hudson: ["Hudson"],
  Hummer: ["H1", "H2", "H3", "Hummer"],
  Hyundai: [
    "Accent",
    "Azera",
    "Elantra",
    "Entourage",
    "Equus",
    "Excel",
    "Genesis",
    "Ioniq",
    "Ioniq 5",
    "Kona",
    "Kona Electric",
    "Nexo",
    "Palisade",
    "Pony",
    "Santa Cruz",
    "Santa Fe",
    "Scoupe",
    "Sonata",
    "Stellar",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Venue",
    "Veracruz",
    "XG Series",
  ],
  IH: ["(Pickup & Travelall)", "Scout & Scout II", "Truck (Big)"],
  Infiniti: [
    "EX35",
    "EX37",
    "FX",
    "G20",
    "G25",
    "G35",
    "G37",
    "I30",
    "I35",
    "J30",
    "JX35",
    "M30",
    "M35",
    "M37",
    "M45",
    "M56",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX30",
    "QX4",
    "QX50",
    "QX55",
    "QX56",
    "QX60",
    "QX70",
    "QX80",
  ],
  Isuzu: [
    "Amigo",
    "Ascender",
    "Axiom",
    "Gemini",
    "IMark",
    "Impulse",
    "Oasis",
    "Optima",
    "Reach",
    "Rodeo",
    "Stylus",
    "Trooper/Trooper II",
    "Truck (Big)",
    "Truck i280 (Pickup)",
    "Truck i290 (Pickup)",
    "Truck i350 (Pickup)",
    "Truck i370 (Pickup)",
    "Truck-(Mini Pickup)",
    "Truck-(Mini Pickup) Hombre",
    "Vehicross",
  ],
  Jaguar: [
    "120",
    "140",
    "150",
    "E Pace",
    "F Pace",
    "F Type",
    "I Pace",
    "Mark 10",
    "S Type",
    "Sedan",
    "Vanden Plas (1997 Down)",
    "Vanden Plas (1998 to 2007)",
    "Vanden Plas (2008 Up)",
    "X Type",
    "XE",
    "XF",
    "XF Sportbrake",
    "XJ Series (2008 Up)",
    "XJ12",
    "XJ6",
    "XJ8 (2007 Down)",
    "XJ8 (2008 Up)",
    "XJR (1993)",
    "XJR (1995 to 1997)",
    "XJR (1998 to 2007)",
    "XJR (2008 Up)",
    "XJS",
    "XK Series (2007 Up)",
    "XK8",
    "XKE",
    "XKR (2006 Down)",
    "XKR (2007 Up)",
  ],
  Jeep: [
    "Cherokee (except Grand Cherokee)",
    "CJSeries",
    "Comanche",
    "Commander",
    "Compass",
    "DJ Series",
    "FC Series",
    "Gladiator",
    "Grand Cherokee",
    "Grand Wagoneer",
    "J-Series",
    "Jeepster",
    "Liberty",
    "Patriot",
    "Renegade",
    "Station Wagon",
    "Truck",
    "Wagoneer (except Grand Wagoneer)",
    "Wrangler",
  ],
  Kaiser: ["Kaiser"],
  Kenworth: ["Kenworth"],
  Kia: [
    "Amanti",
    "Besta",
    "Borrego",
    "Cadenza",
    "Carnival",
    "EV6",
    "Forte",
    "K5",
    "K900",
    "Magentis",
    "Niro",
    "Niro EV",
    "Optima",
    "Rio",
    "Rondo",
    "Sedona",
    "Seltos",
    "Sephia",
    "Sorento",
    "Soul",
    "Spectra",
    "Sportage",
    "Stinger",
    "Telluride",
  ],
  Lada: ["Lada"],
  Lamborghini: ["Lamborghini"],
  Lancia: ["Lancia"],
  LandRover: [
    "Defender (1997 Down)",
    "Defender (2020 Up)",
    "Discovery (2004 Down)",
    "Discovery (2017 Up)",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Other",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: [
    "CT 200H",
    "ES250",
    "ES300",
    "ES300H",
    "ES330",
    "ES350",
    "GS F",
    "GS200t",
    "GS300",
    "GS350",
    "GS400",
    "GS430",
    "GS450",
    "GS460",
    "GX460",
    "GX470",
    "HS250H",
    "IS F",
    "IS200t",
    "IS250",
    "IS300",
    "IS350",
    "IS500",
    "LC500",
    "LC500h",
    "LFA",
    "LS400",
    "LS430",
    "LS460",
    "LS500",
    "LS500h",
    "LS600HL",
    "LX450",
    "LX470",
    "LX570",
    "LX600",
    "NX200t",
    "NX250",
    "NX300",
    "NX300h",
    "NX350",
    "NX350H",
    "NX450H",
    "RC 200t",
    "RC 300",
    "RC 350",
    "RC F",
    "RX300",
    "RX330",
    "RX350",
    "RX350L",
    "RX400h",
    "RX450 Hybrid",
    "RX450 Hybrid L",
    "SC (excl 430)",
    "SC430",
    "UX 200",
    "UX 250h",
  ],
  Lincoln: [
    "Aviator",
    "Blackwood",
    "Continental",
    "Corsair",
    "LS",
    "Mark LT",
    "Mark Series",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Other (includes Town Car)",
    "Versailles",
    "Zephyr",
  ],
  Lotus: ["Lotus"],
  Mac: ["Mac"],
  Marmon: ["Truck"],
  Maserati: ["BiTurbo", "Ghibli", "GranTurismo", "Levante", "Maserati", "Quattroporte"],
  Maybach: ["Maybach"],
  Mazda: [
    "1200",
    "1800",
    "2",
    "3",
    "323",
    "5",
    "6",
    "626",
    "808",
    "929",
    "Cosmo",
    "CX3",
    "CX30",
    "CX5",
    "CX7",
    "CX9",
    "GLC",
    "Miata MX5",
    "Millenia",
    "MPV Van",
    "MX3",
    "MX30",
    "MX6",
    "Navajo",
    "Pickup-B1600",
    "Pickup-B1800",
    "Pickup-B2000",
    "Pickup-B2200",
    "Pickup-B2300",
    "Pickup-B2500",
    "Pickup-B2600",
    "Pickup-B3000",
    "Pickup-B4000",
    "Pickup-Rotary",
    "Protege",
    "RX2",
    "RX3",
    "RX4",
    "RX7",
    "RX8",
    "Tribute",
  ],
  McLaren: ["570GT", "570S", "600LT", "650S", "675LT", "720S", "GT", "MP4 12C", "P1", "Senna"],
  Mercedes: [
    "170",
    "190",
    "200",
    "218",
    "219",
    "220",
    "230-4 Cyl",
    "230-6 Cyl",
    "240D",
    "250",
    "260E",
    "280",
    "300D (includes CD/D/SD/TD)",
    "300E",
    "300SL",
    "320",
    "350",
    "380",
    "400",
    "420",
    "450",
    "500",
    "560",
    "600",
    "A Class",
    "AMG GT",
    "B Class",
    "C Class",
    "CL Class",
    "CLA Class",
    "CLK",
    "CLS",
    "E Class",
    "EQS Class",
    "G Class",
    "GL Class",
    "GLA Class",
    "GLB Class",
    "GLC Class",
    "GLE Class",
    "GLK Class",
    "GLS Class",
    "Metris",
    "ML Series",
    "R Class",
    "S Class",
    "SL Class",
    "SLC Class",
    "SLK",
    "SLR",
    "SLS",
    "Sprinter 1500",
    "Sprinter 2500",
    "Sprinter 3500",
    "Truck",
  ],
  Mercury: [
    "Bobcat",
    "Capri",
    "Comet",
    "Cougar",
    "Grand Marquis (1979 Down)",
    "Grand Marquis (1980 Up)",
    "LN7",
    "Lynx (except LN7)",
    "Marauder",
    "Mariner",
    "Marquis (not Grand)",
    "Merkur (includes XR4TI and Scorpio)",
    "Milan",
    "Monarch",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Other",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
    "Zephyr",
  ],
  MG: ["MGB", "Midget", "Other"],
  Mini: ["(Austin)", "Cooper", "Cooper Clubman", "Cooper Countryman", "Cooper Paceman"],
  Mitsubishi: [
    "3000",
    "Cordia",
    "Diamante",
    "Eclipse",
    "Eclipse Cross",
    "Endeavor",
    "Expo",
    "Fuso",
    "Galant",
    "i MiEV",
    "Lancer",
    "Minicab",
    "Mirage",
    "Montero",
    "Montero-Sport",
    "Outlander",
    "Outlander Sport",
    "Pickup (See also Dodge D50)",
    "Precis",
    "Raider",
    "RVR",
    "Sigma",
    "Space Wagon",
    "Starion",
    "Tredia",
    "Van",
  ],
  Morris: ["Morris"],
  Nash: ["Nash"],
  Nissan: [
    "1200",
    "1600",
    "200SX",
    "210",
    "240SX",
    "240Z",
    "260Z",
    "280-Z",
    "280-ZX",
    "300ZX",
    "310",
    "311",
    "350Z",
    "370Z",
    "410",
    "411",
    "510",
    "610",
    "710",
    "810",
    "Almera",
    "Altima",
    "Armada",
    "Axxess",
    "B210",
    "Cube",
    "F10",
    "Frontier",
    "GTR",
    "Juke",
    "Kicks",
    "Leaf",
    "Lucino",
    "Maxima (1981 Down)",
    "Maxima (1982 Up)",
    "Micra",
    "Murano",
    "NV 1500",
    "NV 200",
    "NV 2500",
    "NV 3500",
    "NX",
    "Pathfinder",
    "Patrol",
    "Platina",
    "Pulsar",
    "Qashqai",
    "Quest",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Stanza (Excl Van)",
    "Stanza Van",
    "Tida",
    "Truck",
    "Truck-Titan",
    "Truck-Titan XD",
    "Tsubame",
    "UD Series",
    "Van GC22",
    "Versa",
    "X Trail",
    "Xterra",
  ],
  Oldsmobile: [
    "88 (1979 Down)",
    "88 (1980 Up)",
    "98 (1979 Down)",
    "98 (1980 Up)",
    "Achieva",
    "Alero",
    "Aurora",
    "Bravada",
    "Calais (1984 Down)",
    "Calais (1985 Up)",
    "Ciera",
    "Custom Cruiser (1979 Down)",
    "Custom Cruiser (1980 Up)",
    "Cutlass (1972 Down)",
    "Cutlass (1973 Up)",
    "F85",
    "Firenza",
    "Intrigue",
    "Omega",
    "Other",
    "Silhouette",
    "Starfire",
    "Supreme (1972 Down)",
    "Supreme (1973-1987)",
    "Supreme-Calais (1988 Up)",
    "Supreme-Cutlass (1988 Up)",
    "Toronado",
  ],
  Opel: ["Opel"],
  Oshkosh: ["Oshkosh"],
  Pace: ["Arrow"],
  Packard: ["Packard"],
  Pantera: ["Pantera"],
  Peterbilt: ["Peterbilt"],
  Peugeot: ["304", "403", "404", "405", "504", "505", "604"],
  Plymouth: [
    "Acclaim",
    "Arrow-Car",
    "Arrow-Truck (See also Dodge D50)",
    "Barracuda",
    "Breeze",
    "Caravelle",
    "Champ",
    "Cricket",
    "Duster (1970-1976)",
    "Duster (1979-1980)",
    "Duster (1985-1987)",
    "Duster (1992-1994)",
    "Grand Fury (1979 Down)",
    "Grand Fury (1980 Up)",
    "Horizon",
    "Laser",
    "Neon",
    "Other",
    "Prowler",
    "Reliant",
    "Sapporo",
    "Scamp (1983 only)",
    "Scamp (except 1983)",
    "Sundance",
    "Trailduster",
    "Valiant",
    "Van 100",
    "Van 150",
    "Van 200",
    "Van 250",
    "Van 300",
    "Van 350",
    "Volare",
    "Voyager",
  ],
  Polestar: ["1", "2"],
  Pontiac: [
    "1000",
    "2000-P/J/Sunbird",
    "6000",
    "Acadian",
    "Astre",
    "Aztek",
    "Bonneville (1979 Down)",
    "Bonneville (1980 Up)",
    "Catalina (1979 Down)",
    "Catalina (1980 Up)",
    "Fiero",
    "Firebird",
    "Firefly",
    "G3",
    "G4",
    "G5",
    "G6",
    "G8",
    "Grand AM",
    "Grand Prix",
    "GTO (New Style)",
    "GTO (Old Style)",
    "Lemans",
    "Matiz",
    "Montana",
    "Other",
    "Parisienne (1979 Down)",
    "Parisienne (1980 Up)",
    "Phoenix",
    "Pursuit",
    "Solstice",
    "Sunbird",
    "Sunburst",
    "Sunfire",
    "Sunrunner",
    "Tempest",
    "Torrent",
    "Trans Sport",
    "Van-Montana",
    "Ventura",
    "Vibe",
    "Wave",
  ],
  Porsche: [
    "356",
    "911/930",
    "912/e",
    "914",
    "918",
    "924",
    "928",
    "944",
    "968",
    "Boxster",
    "Carrera-GT",
    "Cayenne",
    "Cayman S",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  Ram: [
    "Promaster 1500",
    "Promaster 2500",
    "Promaster 3500",
    "Promaster City",
    "Truck 1500 Series",
    "Truck 2500 Series",
    "Truck 3500 Series",
    "Truck 4500 Series",
    "Truck 5500 Series",
  ],
  Renault: [
    "18I",
    "Alliance",
    "Clio",
    "Dauphine",
    "Encore",
    "Fuego",
    "Gordini",
    "Lecar/R5",
    "Medallion",
    "Megane",
    "Other",
    "R10",
    "R12",
    "R15",
    "R16",
    "R17",
    "R30",
    "R8",
  ],
  REO: ["REO"],
  RollsRoyce: ["RollsRoyce"],
  Rover: ["100", "2000", "3 Litre", "3500", "3500S"],
  Saab: [
    "9-3 (1999 Up)",
    "9-5 (1999 Up)",
    "900 (incl Turbo)",
    "9000 (incl Turbo)",
    "92x",
    "93 (1960 Down)",
    "94x",
    "95 (1972 Down)",
    "96",
    "97x",
    "99",
    "Monte Carlo",
    "Sonett",
    "Sonett III",
  ],
  Saturn: ["Astra", "Aura", "EV1", "Ion", "L Series", "Outlook", "Relay", "S Series", "Sky", "Vue"],
  Scion: ["FRS", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
  Seat: ["Cordova", "Ibiza", "Leon", "Toledo"],
  Simca: ["Simca"],
  Smart: ["Fortwo"],
  SterlingRover: ["SterlingRover"],
  Studebaker: ["Studebaker"],
  Subaru: [
    "Ascent",
    "Baja",
    "Brat",
    "BRZ",
    "Chaser",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Justy",
    "Legacy",
    "Loyale",
    "Other",
    "Outback (Impreza)",
    "Outback (Legacy)",
    "Sambar",
    "Streega",
    "SVX",
    "Tribeca",
    "WRX (2014 Down)",
    "WRX (2015 Up)",
    "XT",
    "XV Crosstrek",
  ],
  Sunbeam: ["Sunbeam"],
  Suzuki: [
    "Aerio",
    "Carry",
    "Equator",
    "Esteem",
    "Forenza",
    "Forsa",
    "Kizashi",
    "Reno",
    "Samurai",
    "Sidekick",
    "SJ410",
    "Swift",
    "SX4",
    "Verona",
    "X90",
    "XL7",
  ],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  Thomas: ["Truck"],
  Toyota: [
    "4Runner",
    "86",
    "Aristo",
    "Avalon",
    "Camry",
    "Carina",
    "Celica",
    "CHR",
    "Corolla",
    "Corolla Cross",
    "Corolla FX/FX16",
    "Corolla iM",
    "Corona MKII",
    "Corona not MKII",
    "Cressida",
    "Crown",
    "Echo",
    "FJ Cruiser",
    "FX/FX16",
    "GR86",
    "HiAce",
    "Highlander",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "Paseo",
    "Previa",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Solara",
    "Starlet",
    "Stout",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Truck (except T100 & Tundra)",
    "Tundra",
    "Van (See also Previa)",
    "Venza",
    "Yaris",
    "Yaris iA",
  ],
  Triumph: ["GT6", "Spitfire", "Stag", "TR2", "TR250", "TR3", "TR4", "TR4A", "TR6", "TR7", "TR8"],
  Utilimaster: ["Step Van"],
  Volkswagen: [
    "412/411",
    "Arteon",
    "Atlas",
    "Atlas Cross Sport",
    "Beetle/Bug",
    "Cabrio",
    "Cabriolet",
    "CC",
    "Corrado",
    "Dasher",
    "Derby",
    "Eos",
    "Fox",
    "Golf",
    "Golf GTI",
    "ID.4",
    "Jetta",
    "Jetta GLI",
    "Karmann Ghia",
    "Other",
    "Passat",
    "Phaeton",
    "Pointer",
    "Pointer Truck",
    "Quantum",
    "Rabbit",
    "Routan",
    "Scirocco",
    "Sedan",
    "Sharan",
    "Taos",
    "Thing",
    "Tiguan",
    "Touareg",
    "Type 3",
    "Van-EuroVan",
    "Van-Transporter",
    "Van-Vanagon",
  ],
  Volvo: [
    "120 Series",
    "140 Series",
    "160 Series",
    "1800",
    "240",
    "260",
    "30 Series",
    "40 Series",
    "50 Series",
    "444/445",
    "544",
    "60 Series",
    "70 Series",
    "740",
    "760",
    "780",
    "80 Series",
    "850",
    "90 Series",
    "940",
    "960",
    "C40",
    "F7",
    "FE6",
    "S60 (2013 Down)",
    "S60 (2014 Up)",
    "S90",
    "Truck",
    "V60",
    "V70",
    "V90",
    "XC40",
    "XC60 (2013 Down)",
    "XC60 (2014 Up)",
    "XC70",
    "XC90",
  ],
  VPG: ["MV1"],
  Western: ["Star"],
  White: ["White"],
  Willys: ["Willys"],
  Winnebago: ["Winnebago"],
  Yugo: ["Yugo"],
};