export const parts = [
  { slug: "ac-compressor", name: "AC Compressor", image: "/images/ac-compressor.png", link: "/parts/ac-compressor" },
  { slug: "air-bag", name: "Air Bag", image: "/images/air-bag.png", link: "/parts/air-bag" },
  { slug: "air-filter", name: "Air Filter", image: "/images/air-filter.png", link: "/parts/air-filter" },
  { slug: "bumper", name: "Bumper", image: "/images/bumper.png", link: "/parts/bumper" },
  { slug: "console-front", name: "Console Front", image: "/images/console-front.jpg", link: "/parts/console-front" },
  { slug: "console-rear", name: "Console Rear", image: "/images/console-rear.jpg", link: "/parts/console-rear" },
  { slug: "door", name: "Door", image: "/images/door.jpg", link: "/parts/door" },
  { slug: "door-handle", name: "Door Handle", image: "/images/door-handle.jpg", link: "/parts/door-handle" },
  { slug: "door-handle-in", name: "Door Handle In", image: "/images/door-handle-in.png", link: "/parts/door-handle-in" },
  { slug: "seat-belt", name: "Seat Belt", image: "/images/seat-belt.png", link: "/parts/seat-belt" },
  { slug: "door-mirror", name: "Door Mirror", image: "/images/door-mirror.jpg", link: "/parts/door-mirror" },
  { slug: "drive-shaft-front", name: "Drive Shaft Front", image: "/images/driving-shaft-front.jpg", link: "/parts/drive-shaft-front" },
  { slug: "drive-shaft-rear", name: "Drive Shaft Rear", image: "/images/drive-shaft-rear.jpg", link: "/parts/drive-shaft-rear" },
  { slug: "engine", name: "Engine", image: "/images/engine.png", link: "/parts/engine" },
  { slug: "exhaust-assembly", name: "Exhaust Assembly", image: "/images/exhaust-assembly.jpg", link: "/parts/exhaust-assembly" },
  { slug: "fender", name: "Fender", image: "/images/fender.png", link: "/parts/fender" },
  { slug: "fog-lamp", name: "Fog Lamp", image: "/images/fog-lamp.jpg", link: "/parts/fog-lamp" },
  { slug: "fuse-box", name: "Fuse Box", image: "/images/fuse-box.jpg", link: "/parts/fuse-box" },
  { slug: "glove-box", name: "Glove Box", image: "/images/glove-box.jpg", link: "/parts/glove-box" },
  { slug: "head-lights", name: "Head Lights", image: "/images/headlight.png", link: "/parts/head-lights" },
  { slug: "headrest", name: "Headrest", image: "/images/headrest.jpg", link: "/parts/headrest" },
  { slug: "mirror-rear-view", name: "Mirror Rear view", image: "/images/mirror-rear-view.jpg", link: "/parts/mirror-rear-view" },
  { slug: "radiator", name: "Radiator", image: "/images/radiator.jpg", link: "/parts/radiator" },
  { slug: "seat-front", name: "Seat Front", image: "/images/seat-front.png", link: "/parts/seat-front" },
  { slug: "seat-back", name: "Seat Back", image: "/images/seat-back.jpg", link: "/parts/seat-back" },
  { slug: "signal-fog-lamp", name: "Signal Fog Lamp", image: "/images/signal-fog-lamp.jpg", link: "/parts/signal-fog-lamp" },
  { slug: "speedometer", name: "Speedometer", image: "/images/speedometer.jpg", link: "/parts/speedometer" },
  { slug: "steering", name: "Steering", image: "/images/steering.png", link: "/parts/steering" },
  { slug: "steering-column", name: "Steering Column", image: "/images/steering-column.jpg", link: "/parts/steering-column" },
  { slug: "sunvisor", name: "Sunvisor", image: "/images/sunvisor.jpg", link: "/parts/sunvisor" },
  { slug: "tail-light", name: "Tail Light", image: "/images/tail-light.jpg", link: "/parts/tail-light" },
  { slug: "thermostat-housing", name: "Thermostat Housing", image: "/images/thermostat-housing.jpg", link: "/parts/thermostat-housing" },
  { slug: "transfer-case", name: "Transfer Case", image: "/images/transfer-case.jpg", link: "/parts/transfer-case" },
  { slug: "transmission", name: "Transmission", image: "/images/transmission.png", link: "/parts/transmission" },
  { slug: "wheel", name: "Wheel", image: "/images/wheel.png", link: "/parts/wheel" },
  { slug: "window-glass-motor", name: "Window Glass Motor", image: "/images/window-glass-motor.png", link: "/parts/window-glass-motor" },
];
