export const parts = [
  "A Pillar",
  "A/C Compressor",
  "A/C Compressor Clutch Only",
  "A/C Condenser",
  "A/C Condenser Fan",
  "A/C Control Computer",
  "A/C Evaporator",
  "A/C Evaporator Housing only",
  "A/C Heater Control (see also Radio or TV Screen)",
  "A/C Hose",
  "Accelerator Parts",
  "Adaptive Cruise Projector",
  "Air Bag",
  "Air Bag Clockspring",
  "Air Bag Ctrl Module",
  "Air Box/Air Cleaner",
  "Air Cond./Heater Vents",
  "Air Flow Meter",
  "Air Pump",
  "Air Ride Compressor",
  "Air Shutter",
  "Air Tube/Resonator",
  "Alternator",
  "Amplifier/Radio",
  "Antenna",
  "Anti-Lock Brake Computer",
  "Anti-Lock Brake Pump",
  "Armrest",
  "Ash Tray/Lighter",
  "Audiovisual (A/V) (see also TV Screen)",
  "Automatic Headlight Dimmer",
  "Auto. Trans. Cooler",
  "Axle Actuator (4WD)",
  "Axle Assy Fr (4WD w. Housing)",
  "Axle Assy Rear (w. Housing)",
  "Axle Beam Front (2WD, incl I Beam Susp)",
  "Axle Beam Rear (FWD)",
  "Axle Flange",
  "Axle Housing Only",
  "Axle Shaft",
  "Back Door (above rear bumper)",
  "Back Door Glass",
  "Back Door Handle, Inside",
  "Back Door Handle, Outside",
  "Back Door Hinge",
  "Back Door Moulding",
  "Back Door Trim Panel",
  "Back Glass",
  "Back Glass Regulator",
  "Backing Plate, Front",
  "Backing Plate, Rear",
  "Backup Camera",
  "Backup Light",
  "Battery",
  "Battery Tray",
  "Bed, Pickup",
  "Bed Floor (Pickup)",
  "Bed Front Panel (Pickup)",
  "Bed Liner",
  "Bed Side, Pickup",
  "Bell Housing",
  "Belt Tensioner",
  "Blind Spot Camera",
  "Blower Motor",
  "Brake/Clutch Pedal",
  "Brake Booster",
  "Brake Proportioning Valve",
  "Brake Rotor/Drum, Front",
  "Brake Rotor/Drum, Rear",
  "Brake Shoes/Pads",
  "Bumper Assy (Front) includes cover",
  "Bumper Assy (Rear) includes cover",
  "Bumper Cover (Front)",
  "Bumper Cover (Rear)",
  "Bumper End Cap",
  "Bumper Energy Absorber (Front)",
  "Bumper Energy Absorber (Rear)",
  "Bumper Face Bar (Front)",
  "Bumper Face Bar (Rear)",
  "Bumper Filler Panel",
  "Bumper Guard (Front)",
  "Bumper Guard (Rear)",
  "Bumper Reinforcement (Front)",
  "Bumper Reinforcement (Rear)",
  "Bumper Shock",
  "Cab",
  "Cab Clip, no cowl",
  "Cabin Fuse Box",
  "Caliper",
  "Camera Projector",
  "Camshaft",
  "Camshaft Housing",
  "Carburetor (see also Throttle Body)",
  "Cargo Cover/Shade",
  "Carpet",
  "Carrier (see also Differential)",
  "Carrier Case",
  "CD Player/Radio",
  "Center Cap (Wheel)",
  "Center Pillar",
  "Chassis Control Computer (not Engine)",
  "Clock",
  "Clockspring (Air Bag)",
  "Clutch Cable",
  "Clutch Disc",
  "Clutch Master Cylinder",
  "Coil/Air Spring",
  "Coil/Igniter",
  "Column Switch",
  "Computer Box Engine",
  "Computer Box Not Engine",
  "Condenser",
  "Condenser/Radiator mtd. Cooling Fan",
  "Connecting Rod, Engine",
  "Console, Front",
  "Console, Rear",
  "Control Arm, Front Lower",
  "Control Arm, Front Upper",
  "Control Arm, Rear Lower",
  "Control Arm, Rear Upper",
  "Convertible Top Boot",
  "Convertible Top Lift",
  "Convertible Top Motor",
  "Coolant Pump",
  "Cooling Fan (Rad and Con mtd.)",
  "Core (Radiator) Support",
  "Cowl",
  "Cowl Vent Panel",
  "Crank Pulley (Harmonic Balancer)",
  "Crankshaft",
  "Cruise Control Computer",
  "Cruise Control Servo/Regulator",
  "Cruise Speed Controler",
  "Cylinder Head (Engine)",
  "Dash/Interior/Seat Switch",
  "Dash Bezel",
  "Dash Pad",
  "Dash Panel",
  "Dash Wiring Harness/Misc Electric",
  "Deck Lid",
  "Differential Assembly (see also Carrier)",
  "Differential Case Only",
  "Differential Flange Only",
  "Distributor",
  "Door Back (door above rear bumper)",
  "Door Front",
  "Door Handle, Inside",
  "Door Handle, Outside",
  "Door Rear (side of vehicle)",
  "Door Window Crank Handle",
  "Drag Link",
  "Drive-By-Wire",
  "Drive Shaft, Front",
  "Drive Shaft, Rear",
  "EGR Valve",
  "Electric Door Motor (not Window)",
  "Electric Window Motor",
  "Electrical Part Misc and Wiring",
  "Emblem",
  "Emergency Brake",
  "Engine",
  "Engine Block",
  "Engine Computer",
  "Engine Core",
  "Engine Cover",
  "Engine Cradle",
  "Engine Cylinder Head",
  "Engine Fuse Box",
  "Engine Mounts",
  "Engine Oil Pan",
  "Exhaust Assembly",
  "Exhaust Cross Pipe",
  "Exhaust Fluid Pump",
  "Exhaust Fluid Tank",
  "Exhaust Heat Shield",
  "Exhaust Lead Pipe",
  "Exhaust Manifold",
  "Exhaust Muffler",
  "Exhaust Pipe",
  "Exhaust Resonator",
  "Exhaust Tail Pipe",
  "Fan Blade",
  "Fan Clutch",
  "Fender",
  "Fender Extension/Flare",
  "Fender Inner Liner",
  "Fender Inner Panel",
  "Fender Moulding",
  "Fender Skirt",
  "Flex Plate",
  "Floor Mats",
  "Floor Pan",
  "Floor Shift Assembly",
  "Flywheel",
  "Fog Lamp",
  "Frame",
  "Frame Front Section Only",
  "Frame Horn",
  "Frame Upper & Lower Rails",
  "Front Axle Assembly (4WD w Housing)",
  "Front Axle Beam (2WD, incl I Beam Susp)",
  "Front Axle Shaft",
  "Front Bumper Assembly (includes cover)",
  "Front Bumper Cover",
  "Front Bumper Face Bar",
  "Front Bumper Guard",
  "Front Bumper Reinforcement",
  "Front Console",
  "Front Door",
  "Front Door Glass",
  "Front Door Handle, Inside",
  "Front Door Handle, Outside",
  "Front Door Hinge",
  "Front Door Mirror",
  "Front Door Moulding",
  "Front Door Regulator",
  "Front Door Switch",
  "Front Door Trim Panel",
  "Front Door Vent Glass",
  "Front Door Vent Glass Regulator",
  "Front Door Window Motor",
  "Front Drive Shaft",
  "Front End Assembly (Nose)",
  "Front Seat Belt Assembly",
  "Front Valance",
  "Front Window Regulator",
  "Fuel Cap",
  "Fuel Cell",
  "Fuel Distributor (& Misc. Injection)",
  "Fuel Filler Door",
  "Fuel Filler Neck",
  "Fuel Gauge",
  "Fuel Injector (& Misc. Injection)",
  "Fuel Injector Pump",
  "Fuel Line",
  "Fuel Pump",
  "Fuel Rail (& Misc. Injection)",
  "Fuel Tank",
  "Fuel Tank Sending Unit",
  "Fuse Box (Cabin)",
  "Fuse Box (Engine)",
  "Gas Cap",
  "Gas Tank",
  "Gate Interior Trim Panel",
  "Gate Window Regulator",
  "Gate/Lid",
  "Gauge (Misc)",
  "Generator",
  "Glass, Back",
  "Glass, Front Door",
  "Glass, Front Vent",
  "Glass, Quarter Window",
  "Glass, Rear Door",
  "Glass, Rear Vent",
  "Glass, Special (see also Sunroof/TTop)",
  "Glass, Windshield",
  "Glove Box",
  "GPS Screen (see also Radio or Heater/AC Control)",
  "Grille",
  "Harmonic Balancer (Crank Pulley)",
  "Hatch/Trunk Lid",
  "Head (Cylinder)",
  "Header Panel",
  "Headlight Assembly",
  "Headlight Door",
  "Headlight Motor",
  "Headlight Switch (Dash)",
  "Headlight Switch (see also Column Switch)",
  "Headlight Washer Motor Only",
  "Headlight Wiper Motor Only",
  "Headliner",
  "Headrest",
  "Heads Up Display",
  "Heater Assy",
  "Heater Core",
  "Heater Motor",
  "Heater/AC Control (see also Radio or TV Screen)",
  "Hood",
  "Hood Hinge",
  "Hood Ornament",
  "Hood Scoop",
  "Hood Shock",
  "Horn",
  "Hub",
  "Hub Cap/Wheel Cover (display w image)",
  "Hub Cap/Wheel Cover (display w/o image)",
  "Hub, Lockout (4WD)",
  "Hybrid Converter/Inverter",
  "Idler Arm",
  "Ignition Module (see also Ignitor/Coil)",
  "Ignition Switch",
  "Ignitor/Coil",
  "Info Screen (see also Radio or Heater/AC Control)",
  "Inside Door Handle",
  "Instrument Cluster (see also Speedo)",
  "Intake Manifold",
  "Intercooler",
  "Interior Complete",
  "Interior Light",
  "Interior Trim Panel (Gate/Lid)",
  "Interior Trim Panel (Quarter)",
  "Interior Trim Panel, Door (Back)",
  "Interior Trim Panel, Door (Front)",
  "Interior Trim Panel, Door (Rear)",
  "Inverter Cooler",
  "Jack Assembly",
  "Keys/Latches and Locks",
  "Key Remote/Fob",
  "Knee Assembly (see also Strut Assy)",
  "Latches",
  "Leaf Spring, Front",
  "Leaf Spring, Rear",
  "License Lamp",
  "Lid/Gate",
  "Lid Interior Trim Panel",
  "Lock Actuator",
  "Lockout Hub, 4X4",
  "Locks",
  "Luggage Rack",
  "Marker/Fog Light, Front",
  "Marker/Side Light, Rear",
  "Master Cylinder",
  "Mirror, Door",
  "Mirror, Rear View",
  "Moulding (Back Door)",
  "Moulding (Fender)",
  "Moulding (Front Door)",
  "Moulding (Lid/Hatch/Gate)",
  "Moulding (Quarter Panel/Bed Side)",
  "Moulding (Rear Door)",
  "Moulding (Rocker)",
  "Moulding (Windshield)",
  "Mouldings (Misc)",
  "Night Vision Camera",
  "Nose (Front End Assembly)",
  "Oil Cooler",
  "Oil Filter Adapter",
  "Oil Pan, Engine",
  "Oil Pan, Transmission",
  "Oil Pump, Engine",
  "Outside Door Handle",
  "Overdrive Unit (see also Transmission)",
  "Owners Manual",
  "Park/Fog Lamp Front",
  "Parcel Shelf",
  "Park Lamp Rear (Side)",
  "Parking Assist Camera",
  "Pickup Bed",
  "Pickup Bed Floor",
  "Pickup Bed Front Panel",
  "Pickup Bed Side",
  "Pickup Cap/Camper Shell",
  "Piston",
  "Pitman Arm",
  "Power Brake Booster",
  "Power Inverter (Hybrid)",
  "Power Steering Assy",
  "Power Steering Control Valve",
  "Power Steering Cooler",
  "Power Steering Motor",
  "Power Steering Pressure Cyl",
  "Power Steering Pressure Hose",
  "Power Steering Pump",
  "Power Steering Rack/Box/Gear",
  "Power Steering Reservoir",
  "Pressure Plate",
  "Quarter Interior Trim Panel",
  "Quarter Moulding",
  "Quarter Panel",
  "Quarter Panel Extension",
  "Quarter Repair Panel",
  "Quarter Window",
  "Quarter Window Motor",
  "Quarter Window Regulator",
  "Rack & Pinion (Steering)",
  "Radiator",
  "Radiator/Condenser mtd. Cooling Fan",
  "Radiator Air Shutter",
  "Radiator Core Support",
  "Radiator Cover Baffle",
  "Radiator Fan Shroud",
  "Radiator Overflow Bottle",
  "Radio/CD (see also A/C Control or TV Screen)",
  "Radius Arm, Front",
  "Rag Joint (see also Steering Coupler)",
  "Rear Axle Assy (RWD)",
  "Rear Axle Beam (FWD)",
  "Rear Body Panel",
  "Rear Bumper Assembly (includes cover)",
  "Rear Bumper Cover",
  "Rear Bumper Face Bar",
  "Rear Bumper Guard",
  "Rear Bumper Reinforcement/Misc",
  "Rear Clip",
  "Rear Console",
  "Rear Crossmember",
  "Rear Door (side of vehicle)",
  "Rear Door Handle, Inside",
  "Rear Door Handle, Outside",
  "Rear Door Hinge",
  "Rear Door Moulding",
  "Rear Door Regulator",
  "Rear Door Switch",
  "Rear Door Trim Panel",
  "Rear Door Vent Glass",
  "Rear Door Vent Glass regulator",
  "Rear Door Window",
  "Rear Door Window Motor",
  "Rear Door Window Regulator",
  "Rear Drive Shaft",
  "Rear Finish Panel",
  "Rear Gate/Lid",
  "Rear Gate Window Motor",
  "Rear Knuckle/Stub Axle",
  "Rear Lower Valance",
  "Rear Seat Belt Assembly",
  "Rear Suspension (see also Control Arms)",
  "Rear Suspension Locating Arm",
  "Rear Suspension Trailing Arm",
  "Rear Window Defogger",
  "Rear Window Washer Motor",
  "Relay (Misc)",
  "Ring and Pinion Only",
  "Rocker Arm",
  "Rocker Moulding",
  "Rocker Panel (see also Center Pillar)",
  "Roll Bar",
  "Roof",
  "Roof Panel (see also Sunroof)",
  "Roof Rack",
  "Running Boards",
  "Seat, Back (3rd)",
  "Seat, Front",
  "Seat, Rear (2nd)",
  "Seat Belt, Front",
  "Seat Belt, Rear",
  "Seat Belt Motor",
  "Seat Belt Track (Electric)",
  "Seat Motor",
  "Seat Switch",
  "Seat Track, Front Only",
  "Sensor (Body, Misc)",
  "Sensor (Chassis, Misc)",
  "Sensor (Drivetrain, Misc)",
  "Shifter Assembly (Floor)",
  "Shifter Linkage",
  "Shock Absorber",
  "Slave Cylinder",
  "Smog Pump",
  "Spare Tire Carrier",
  "Speaker",
  "Special Glass",
  "Speedometer (see also Instr. Cluster)",
  "Spindle",
  "Spoiler, Front",
  "Spoiler, Rear",
  "Spring Hanger",
  "Stabilizer Bar Only",
  "Starter",
  "Steering Column",
  "Steering Coupler",
  "Steering Knuckle (see also Knee & Strut)",
  "Steering Pump",
  "Steering Rack/Box/Gear",
  "Steering Wheel",
  "Strut (see also Knee Assy)",
  "Strut Tower Brace",
  "Sun Roof / T-Top",
  "Sun Roof Motor",
  "Sunvisor",
  "Supercharger/Turbocharger",
  "Tachometer",
  "Tail Light",
  "Tailgate/Trunk Lid",
  "Tailgate Hinge",
  "Tailgate Lift Motor",
  "Thermostat Housing",
  "Third Brake Light",
  "Throttle Body/Throttle Valve Housing",
  "Tie Rod",
  "Timing Belt/Chain",
  "Timing Cover",
  "Timing Gears",
  "Tire",
  "Tonneau Cover",
  "Torque Convertor",
  "Torsion Bar",
  "Trailer Hitch/Tow Hook/Winch",
  "Trans OD Unit (see also Transmission)",
  "Transaxle Housing Only",
  "Transfer Case",
  "Transfer Case Adapter",
  "Transfer Case Core",
  "Transfer Case Electric Motor",
  "Transfer Case Switch",
  "Transmission",
  "Transmission Bellhousing Only",
  "Transmission Computer",
  "Transmission Core",
  "Transmission Crossmember",
  "Transmission Front Pump",
  "Transmission Mount",
  "Transmission Pan",
  "Transmission Torque Converter",
  "Trim Ring",
  "Trunk Lid Pull Down Motor",
  "Trunk Lid/Hatch",
  "Trunk Lid/Hatch Hinge",
  "Trunk Lid/Hatch Shock",
  "Trunk Lid/Tailgate Moulding",
  "TTop/Sunroof",
  "Turbo/Supercharger Core",
  "Turbocharger/Supercharger",
  "Turn Signal/Fog Lamp",
  "TV Screen (see also Radio or Heater/AC Control)",
  "Uniside",
  "Vacuum Pump",
  "Vacuum Storage Tank",
  "Valance, Front",
  "Valance, Rear",
  "Valve Cover",
  "Vapor Canister",
  "Voltage Regulator",
  "Water Pump",
  "Water Separator",
  "Wheel (display w image)",
  "Wheel (display w/o image)",
  "Wheel Cover/Hubcap (display w image)",
  "Wheel Cover/Hubcap (display w/o image)",
  "Window Motor",
  "Window Regulator (Front)",
  "Window Regulator (Rear)",
  "Window Shade",
  "Window Switch (Front Door)",
  "Window Switch (Rear Door)",
  "Window Washer Motor, Rear",
  "Windshield",
  "Windshield Frame",
  "Windshield Washer Motor (Front)",
  "Windshield Washer Reservoir",
  "Wiper Arm",
  "Wiper Linkage",
  "Wiper Motor, Front (Windshield)",
  "Wiper Motor, Rear",
  "Wiring Harness/Misc. Electric",
  "Yoke/U-Joint",
];